# Generated by Django 5.1.7 on 2025-03-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Accepted', max_length=15),
        ),
    ]
